

### Get all users

GET http://localhost:3001/api/users

### get user by id and populated thought and friend data
GET http://localhost:3001/api/users/62fd795706272aa5b79a12ae

### Create/post a User
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "lernantino",
  "email": "lernantino@gmail.com"
}
###update a user by its _id
PUT http://localhost:3001/api/users/62fd795706272aa5b79a12ae
Content-Type: application/json

{
  "username": "lernantino2",
  "email": "lernantino@gmail.com"
}

### delete a user by its _id

DELETE http://localhost:3001/api/users/62fd795706272aa5b79a12ae




### get all thoughts

GET http://localhost:3001/api/thoughts

### Add student to a group

POST https://mongoose-playground-testing.herokuapp.com/api/students/
Content-Type: application/json

{
  "group_id": "62fd0d7f8e7b2c4c319bba4c",
  "first": "test",
  "last": "test123123"
}

###

DELETE http://localhost:3001/api/students/
Content-Type: application/json

{
  "group_id": "62fab3ae7195131226d24df2",
  "student_id": "62fab3e07195131226d24df5"
}