GET http://localhost:3001/api/users

### Create a group
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "lernantino",
  "email": "lernantino@gmail.com"
}

### Add student to a group

POST https://mongoose-playground-testing.herokuapp.com/api/students/
Content-Type: application/json

{
  "group_id": "62fd0d7f8e7b2c4c319bba4c",
  "first": "test",
  "last": "test123123"
}

###

DELETE http://localhost:3001/api/students/
Content-Type: application/json

{
  "group_id": "62fab3ae7195131226d24df2",
  "student_id": "62fab3e07195131226d24df5"
}